#!/usr/bin/env python

from flask import Flask, Response, request, jsonify
import dill

app = Flask(__name__)

@app.route("/ping", methods=["GET"])
def ping():
    return Response(response="\n", status=200)

@app.route("/invocations", methods=["POST"])
def predict():
    payload = request.json["x"]
    predict = model.predict(payload)
    return Response(response=str(predict), status=200)

if __name__ == "__main__":
    with open("model.dill", "rb") as f:
        model = dill.load(f)
    app.run(host="0.0.0.0", port=8080)