#!/usr/bin/env Rscript

serve <- function() {
    app <- plumber::plumb('/opt/ml/plumber.R')
    app$run(host='0.0.0.0', port=8080)
}

# Run at start-up
args <- commandArgs()
if (any(grepl('serve', args))) {
    serve()}