#!/usr/bin/env Rscript

prefix <- "/opt/ml/"
#prefix <- ""

serve <- function() {
    app <- plumber::plumb(paste0(prefix, 'plumber.R'))
    app$run(host='0.0.0.0', port=8080)
}

# Run at start-up
args <- commandArgs()
if (any(grepl('serve', args))) {
    serve()}